### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [2]:
import numpy as np
prime_numbers = [n for n in range(2, 20) if all(n % i != 0 for i in range(2, n))]
primes = np.array(prime_numbers)
primes[primes>10], primes[primes%2==0]

(array([11, 13, 17, 19]), array([2]))

### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [3]:
array_2d = np.random.randint(1, 10, (5, 5))
b_1 = array_2d[1, :]
b_2 = array_2d[3, :]
c = array_2d[2, :]
d = array_2d / c.reshape(-1, 1)
array_2d, b_1, b_2, c, d

(array([[8, 3, 3, 2, 7],
        [2, 2, 2, 4, 3],
        [4, 9, 5, 4, 2],
        [6, 9, 1, 4, 5],
        [4, 7, 9, 5, 1]]),
 array([2, 2, 2, 4, 3]),
 array([6, 9, 1, 4, 5]),
 array([4, 9, 5, 4, 2]),
 array([[2.        , 0.75      , 0.75      , 0.5       , 1.75      ],
        [0.22222222, 0.22222222, 0.22222222, 0.44444444, 0.33333333],
        [0.8       , 1.8       , 1.        , 0.8       , 0.4       ],
        [1.5       , 2.25      , 0.25      , 1.        , 1.25      ],
        [2.        , 3.5       , 4.5       , 2.5       , 0.5       ]]))

### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [4]:
array_2d = np.random.random((10, 3))
array_2d[1,  :]
print(f"Array: {array_2d}")
for line in range(len(array_2d)):
    print(f"Line {line+1}: {array_2d[line, :][np.abs(array_2d[line, :] - 0.5).argmin()]}")

Array: [[3.41174748e-01 4.44382181e-01 1.09639845e-01]
 [1.04677443e-01 4.04819166e-01 2.83739561e-02]
 [9.19245588e-01 8.21388019e-01 3.27051671e-01]
 [4.23228997e-01 4.73202284e-01 8.75010529e-01]
 [8.48671541e-02 9.92956306e-01 9.88562137e-01]
 [6.68538502e-01 5.96464661e-01 9.18300314e-01]
 [4.08522630e-01 1.93233732e-01 9.44853340e-01]
 [4.77562511e-01 6.94179706e-01 4.17613495e-01]
 [9.81544585e-01 8.70249527e-01 4.29779097e-01]
 [8.00034338e-01 2.72813099e-04 8.13982221e-02]]
Line 1: 0.4443821813740524
Line 2: 0.4048191655745541
Line 3: 0.32705167133829505
Line 4: 0.47320228351703086
Line 5: 0.08486715409377699
Line 6: 0.5964646606682336
Line 7: 0.4085226303280801
Line 8: 0.4775625106483371
Line 9: 0.4297790973057046
Line 10: 0.800034337963981


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [5]:
heart_frequency = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])
minValue = heart_frequency.min()
maxValue = heart_frequency.max()
reads = heart_frequency > 120
percentage = np.sum(reads) / len(heart_frequency) * 100
minValue, maxValue, percentage

(60, 164, 52.38095238095239)

### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [6]:
salaries = np.array([50_000, 105_250, 55_000, 89_000])
totalA = np.sum(salaries)
print(f"Total: {totalA}")
salaries[salaries == 105_250] = salaries[salaries == 105_250] * 1.15
# non viene conservata la parte decimale essendo un array di interi

salaries = np.array([50_000, 105_250, 55_000, 89_000], dtype=np.float32)
salaries[salaries == 105_250] *= 1.15
salaries[salaries == 50_000] *= 1.2
salaries[~np.isin(np.round(salaries, 2), [60_000, 121_037.50])] *= 1.1
totalB = np.sum(salaries)
print(f"Total: {totalB}")

print(f"Difference: {totalB-totalA}")


salaries

Total: 299250
Total: 339437.5
Difference: 40187.5


array([ 60000.004, 121037.5  ,  60500.   ,  97900.   ], dtype=float32)

### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [13]:
co2_emissions = np.round(np.random.uniform(4, 20, 200), 2)
output_file = "localdataset/co2.txt"
np.savetxt(output_file, co2_emissions, fmt="%.2f")
co2_emissions, output_file

(array([19.37, 19.98, 14.36,  5.49,  4.45, 10.34, 17.85,  5.09, 11.81,
        17.88,  9.  , 18.23, 13.36, 11.16,  7.18, 17.52, 19.93, 12.79,
        19.23,  9.98,  9.86, 13.94, 10.12,  4.1 , 12.49, 13.16, 10.63,
        14.64,  6.43, 13.26, 17.11, 10.1 , 13.9 ,  8.36,  5.91,  9.71,
         6.75, 15.74, 12.79, 11.7 ,  5.29,  4.29, 12.92,  4.23,  8.88,
         9.77,  7.79, 11.14,  9.95, 15.79,  6.36, 10.2 , 14.81, 17.71,
        19.35, 12.87,  6.45,  5.92,  8.43,  8.67,  4.3 , 19.59, 12.76,
        19.91, 10.19,  5.7 ,  6.59, 11.4 ,  4.73, 18.99, 11.77,  4.91,
        16.38, 17.79,  9.12,  8.17,  5.34,  9.2 ,  8.8 , 13.36, 16.39,
        19.81, 18.16,  9.53, 15.16,  8.83, 10.05,  7.19,  4.57, 17.04,
        13.03, 15.25, 13.82,  7.64, 11.24, 17.67,  6.82,  6.9 , 13.7 ,
        10.32,  4.59, 17.34, 19.34,  8.39, 10.81, 16.53,  8.24,  8.36,
        19.04, 15.28, 16.79, 18.79, 10.46,  4.04, 11.51, 14.67,  4.53,
         6.31, 12.26, 18.4 , 16.51,  9.45, 10.05,  9.46, 17.95,  6.7 ,
      

In [15]:
co2_emissions = np.loadtxt(output_file)
highCO2 = co2_emissions[co2_emissions > 10]
len(highCO2), highCO2.mean(), len(highCO2)/len(co2_emissions)

(126, 14.873730158730158, 0.63)

### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [ ]:
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])

survey_matrix[survey_matrix[:, 2] >= 12], survey_matrix[survey_matrix[:, 2] >= 12][:, 1], survey_matrix[survey_matrix[:, 2] >= 12][:, 1].mean()

(array([[   32, 52000,    12],
        [   40, 63000,    14],
        [   35, 58000,    13]]),
 array([52000, 63000, 58000]),
 57666.666666666664)

### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [ ]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])


ages = ages[ages != 999]
ages

array([ 92, 108,  75,  63,  62,  66,  90,  98,  97,  92,  60, 107,  90,
        71,  97,  86,  55,  55,  98,  57,  96, 104,  96,  94,  72,  98,
       111,  98,  89,  69,  77,  92,  85, 101,  93, 100,  90, 101,  96,
        98,  87, 106,  86, 108,  55,  67,  65,  68,  59,  67,  72,  57,
        79,  95,  67,  86,  70,  91, 111,  67,  75,  59,  88,  90,  99,
        94,  65, 111, 103, 100,  70,  63,  65, 100, 110,  70,  57,  75,
        56, 104, 111,  90,  74, 100,  90,  86,  88,  99,  58, 103,  88,
       103,  64,  96, 105,  89,  83,  65, 100,  62,  73, 105,  83, 105,
        58,  96,  77,  74,  95, 109,  91, 101,  91,  63, 111,  97, 108,
        75,  77,  73,  58,  94,  83,  90,  61, 110, 107, 105,  85,  64,
        66,  71, 107, 105,  72,  78,  66, 100, 102,  72,  74,  68,  73,
        72,  90,  93,  99,  55,  92,  83,  58,  71,  89,  75,  98,  87,
        78,  97,  71, 106,  83,  58,  81, 100,  72,  93,  70,  65,  60,
        95, 107,  94,  77,  87,  90,  82,  56,  99, 107,  86,  5

### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [ ]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

random_words = np.random.choice(lista_parole, 5, replace=True)

print("In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico %s che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il %s come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, \"%s\".\nRadunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un %s.\"\nNel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.   Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: \"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza %s!\" Ci fu grande gioia e celebrazione." % tuple(random_words))

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico BATTERIA che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il INSEDIAMENTO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "ALFABETIZZAZIONE".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un DIFFERENZA."
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.   Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza SEPARAZIONE!" Ci fu grande gioia e celebrazione.


Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."